<a href="https://colab.research.google.com/github/sau113/Dataset_tomato/blob/master/Trainer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import glob
import numpy as np
from tensorflow.keras import layers
from tensorflow import keras 
import tensorflow as tf

from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense


network = Sequential()

network.add(Convolution2D(64,(3,3),input_shape = (64,64,3),activation = 'relu'))

network.add(MaxPooling2D(pool_size = (2,2)))

network.add(Convolution2D(128, (3, 3), activation = 'relu'))
network.add(MaxPooling2D(pool_size = (2, 2)))

network.add(Convolution2D(256, (3, 3), activation = 'relu'))
network.add(MaxPooling2D(pool_size = (2, 2)))

network.add(Convolution2D(512, (3, 3), activation = 'relu'))
network.add(MaxPooling2D(pool_size = (2, 2)))


network.add(Flatten())

network.add(Dense(output_dim = 1024, activation = 'relu'))
network.add(Dense(output_dim = 1024, activation = 'relu'))
network.add(Dense(output_dim = 6, activation = 'softmax'))

network.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

from keras.preprocessing.image import ImageDataGenerator

train_data = ImageDataGenerator(rescale = 1./255, 
                                shear_range = 0.2,
                                zoom_range = 0.2,
                                horizontal_flip = True)

valid_data = ImageDataGenerator(rescale = 1./255)



! git clone https://github.com/sau113/Dataset_tomato.git


  
training_set = train_data.flow_from_directory('Dataset_tomato/Training_set',
                                              target_size = (64,64),
                                              batch_size = 10,
                                              class_mode = "categorical")

imgs, labels = next(training_set)

print(labels[:,:])

valid_set= valid_data.flow_from_directory('Dataset_tomato/Validation_set',
                                          target_size = (64,64),
                                          batch_size=10,
                                          class_mode="categorical")






network.fit_generator(training_set,
                      steps_per_epoch = (5520+800)/10,
                      epochs = 25 ,
                      validation_data = valid_set,
                      validation_steps = (4920+200)/10)



network.save('train_data.h5')


Instructions for updating:
Colocations handled automatically by placer.


Using TensorFlow backend.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:33: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=1024)`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:34: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=1024)`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:35: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=6)`


Cloning into 'Dataset_tomato'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 11590 (delta 0), reused 2 (delta 0), pack-reused 11587
Receiving objects: 100% (11590/11590), 299.66 MiB | 29.65 MiB/s, done.
Resolving deltas: 100% (62/62), done.
Checking out files: 100% (11451/11451), done.
Found 6317 images belonging to 6 classes.
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]]
Found 5117 images belonging to 6 classes.
Instructions for updating:
Use tf.cast instead.
Epoch 1/25
632/632 [==============================] - 57s 90ms/step - loss: 1.0664 - acc: 0.5991 - val_loss: 0.6649 - val_acc: 0.7712
Epoch 2/25
632/632 [==============================] - 51s 80ms/step - loss: 0.7624 - acc: 0.7214 - val_loss: 0.7870 - val_acc: 0.7647
Epo

MessageError: ignored