<a href="https://colab.research.google.com/github/sau113/Dataset_tomato/blob/master/Trainer2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import os
import glob
import numpy as np
from tensorflow.keras import layers
from tensorflow import keras 
import tensorflow as tf

from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

from sklearn.preprocessing import LabelEncoder

from keras.utils import np_utils

network = Sequential()

network.add(Convolution2D(32,3,3,input_shape = (64,64,3),activation = 'relu'))

network.add(MaxPooling2D(pool_size = (2,2)))

network.add(Convolution2D(32, 3, 3, activation = 'relu'))
network.add(MaxPooling2D(pool_size = (2, 2)))

network.add(Convolution2D(32, 3, 3, activation = 'relu'))
network.add(MaxPooling2D(pool_size = (2, 2)))

network.add(Flatten())

network.add(Dense(output_dim = 128, activation = 'relu'))
network.add(Dense(output_dim = 64, activation = 'relu'))
network.add(Dense(output_dim = 6, activation = 'sigmoid'))

network.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

from keras.preprocessing.image import ImageDataGenerator

train_data = ImageDataGenerator(rescale = 1./255, 
                                shear_range = 0.2,
                                zoom_range = 0.2,
                                horizontal_flip = True)

valid_data = ImageDataGenerator(rescale = 1./255)



! git clone https://github.com/sau113/Dataset_tomato.git


  
training_set = train_data.flow_from_directory('Dataset_tomato/Training_set',
                                              target_size = (64,64),
                                              batch_size = 10,
                                              class_mode = "categorical")

imgs, labels = next(training_set)

print(labels[:,:])

valid_set= valid_data.flow_from_directory('Dataset_tomato/Validation_set',
                                          target_size = (64,64),
                                          batch_size=10,
                                          class_mode="categorical")






network.fit_generator(training_set,
                      steps_per_epoch = (5520+800)/10,
                      epochs = 5 ,
                      validation_data = valid_set,
                      validation_steps = (4920+200)/10)


% cd Dataset_tomato
network.save('train_data.h5')

! ls

[[0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
